POST http://localhost:5003/purchase
Content-Type: application/json

{
	"variables": {
        "orderId": {
            "value":"@£@$€aækshdlahd",
            "type":"string"
        },
        "customer": {
            "value":"dora@mail.com",
            "type":"string"
        },
		"price": {
			"value":2000,
			"type":"long"
		}
	}
}